import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container, Navbar } from "../lib/components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <Container>
          <h1>ello</h1>
        </Container>
      </main>
    </div>
  );
};

export default Home;
