export const travel = [
  "ASR",
  "Ditzo",
  "Europeesche",
  "De Internationale",
  "FBTO",
  "Centraal Beheer",
  "InShared",
  "Interpolis",
  "DeFriesland",
  "HEMA",
  "Aegon",
  "Allianz Global Assistence",
  "Allianz Direct",
  "Klaverblad",
  "OHRA",
  "Nationale Nederlanden",
  "Unigarant",
  "ANWB",
  "AON",
  "Univé",
  "SNS",
  "De Goudse",
  "Promovendum",
];

export const travelSorted = [
  "No",
  "Yes, but don't know",
  ...travel.sort((a, b) => a.localeCompare(b)),
  "Other",
];

export const health = [
  "VGZ",
  "Zilveren Kruis",
  "CZ",
  "Menzis",
  "ONVZ",
  "FBTO",
  "Ditzo",
  "Univé",
  "OHRA",
  "Klaverblad",
  "DSW",
  "Anderzorg",
  "De Amersfoortse",
  "De Friesland",
  "Hema",
  "Interpolis",
  "IZA",
  "Jaaah",
  "Just",
  "Nationale Nederlanden",
  "Pro Life",
  "Promovendum",
  "Salland",
  "Stad Holland",
  "Studenten Goed Verzekerd",
  "VinkVink",
  "VvAA",
  "ZEKUR",
  "ZieZo",
  "Zorg en Zekerheid",
  "ZorgDirect",
  "UMC",
  "Achmea",
  "Aegon",
];

export const healthSorted = [
  ...health.sort((a, b) => a.localeCompare(b)),
  "Other",
];

export const banks = [
  "ABN Amro",
  "ASN",
  "Bunq",
  "ING",
  "NIBC",
  "Rabobank",
  "RegioBank",
  "SNS Bank",
  "Triodos",
  "Van Lanschot",
  "Other",
];
